# Generated by Django 5.2.6 on 2025-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('status', models.CharField(max_length=15, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
            },
        ),
    ]
