# Generated by Django 5.2.7 on 2025-11-13 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carros', '0002_initial'),
        ('Clientes', '0001_initial'),
        ('Relatorio', '0001_initial'),
        ('funcionarios', '0002_alter_funcionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número da Vaga')),
                ('status', models.CharField(choices=[('L', 'Livre'), ('O', 'Ocupada'), ('M', 'Manutenção')], default='L', max_length=1, verbose_name='Status')),
                ('carro_estacionado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carros.carro', verbose_name='Carro Estacionado')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento_final', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('PIX', 'Pix')], max_length=10, null=True)),
                ('data_hora_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo (Veículo no Local)'), ('CONCLUIDO', 'Concluído (Saída Registrada)')], default='ATIVO', max_length=50, verbose_name='Status da Sessão')),
                ('periodo_estimado', models.CharField(choices=[('HORA', 'Por Hora'), ('DIARIA', 'Diária'), ('MENSAL', 'Mensal')], default='HORA', max_length=50, verbose_name='Período de Cobrança Estimado')),
                ('pagamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total Pago')),
                ('tempo_permanencia', models.DurationField(blank=True, null=True, verbose_name='Tempo de Permanência')),
                ('relatorio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Relatório / Observações')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Carros.carro', verbose_name='Veículo Estacionado')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Clientes.cliente', verbose_name='Cliente/Mensalista')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='funcionarios.funcionario', verbose_name='Funcionário (Entrada)')),
                ('relatorio_final', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_estacionamento', to='Relatorio.relatorio')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vagas.vaga', verbose_name='Vaga Ocupada')),
            ],
            options={
                'verbose_name': 'Registro de Estacionamento',
                'verbose_name_plural': 'Registros de Estacionamento',
            },
        ),
    ]
