# Generated by Django 5.2.7 on 2025-11-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacionamento',
            options={'permissions': (('registrar_entrada', 'Pode registrar a entrada de um veículo no estacionamento'), ('finalizar_saida', 'Pode calcular e finalizar a saída e pagamento do veículo'), ('visualizar_vagas', 'Pode visualizar o mapa de vagas e registros ativos')), 'verbose_name': 'Registro de Estacionamento', 'verbose_name_plural': 'Registros de Estacionamento'},
        ),
    ]
