# Generated by Django 5.2.6 on 2025-09-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('estacionamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estacionamentos.estacionamento')),
                ('tipo', models.CharField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('estacionamentos.estacionamento',),
        ),
    ]
