# Generated by Django 5.2.6 on 2025-09-24 17:33

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas_fisicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas_fisicas.pessoafisica')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='funcionarios', variations={}, verbose_name='foto')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_admissao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
            bases=('pessoas_fisicas.pessoafisica',),
        ),
    ]
