# Generated by Django 5.2.7 on 2025-11-19 00:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Salário base do funcionário', max_digits=8, verbose_name='Salário')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Digite o CPF do Funcionário', max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': [django.db.models.functions.text.Upper('nome')],
                'permissions': (('visualizar_funcionario', 'Pode visualizar a lista de funcionários'), ('cadastrar_funcionario', 'Pode cadastrar novos funcionários'), ('editar_funcionario', 'Pode editar funcionários existentes'), ('deletar_funcionario', 'Pode deletar funcionários')),
            },
        ),
    ]
