# Generated by Django 5.2.7 on 2025-11-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_cnpj',
            field=models.CharField(blank=True, help_text='Digite o CPF do Funcionário', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome'),
        ),
    ]
