# Generated by Django 5.2.7 on 2025-11-18 12:37

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_cpf_cnpj_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'permissions': (('visualizar_funcionario', 'Pode visualizar a lista de funcionários'), ('cadastrar_funcionario', 'Pode cadastrar novos funcionários'), ('editar_funcionario', 'Pode editar funcionários existentes'), ('deletar_funcionario', 'Pode deletar funcionários')), 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
