# Generated by Django 5.2.6 on 2025-09-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pessoas.pessoa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Pessoa_Juridica',
                'verbose_name_plural': 'Pessoas_Juridicas',
            },
            bases=('Pessoas.pessoa',),
        ),
    ]
