# Generated by Django 5.2.6 on 2025-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.FloatField(max_length=10, verbose_name='Valor Hora')),
                ('valor_pernoite', models.FloatField(max_length=10, verbose_name='Valor Pernoite')),
                ('valor_afiliado', models.FloatField(max_length=10, verbose_name='Valor Afiliado')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
