# Generated by Django 5.2.7 on 2025-11-19 00:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Relatório de Pagamento',
                'verbose_name_plural': 'Relatórios de Pagamentos',
                'permissions': (('visualizar_relatorio', 'Pode visualizar relatórios de movimentação e ganhos'), ('exportar_relatorio', 'Pode exportar relatórios para arquivo')),
            },
        ),
    ]
