# Generated by Django 5.2.7 on 2025-11-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorio',
            options={'permissions': (('visualizar_relatorio', 'Pode visualizar relatórios de movimentação e ganhos'), ('exportar_relatorio', 'Pode exportar relatórios para arquivo')), 'verbose_name': 'Relatório de Pagamento', 'verbose_name_plural': 'Relatórios de Pagamentos'},
        ),
    ]
