# Generated by Django 5.2.7 on 2025-11-12 16:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa', models.CharField(help_text='Placa do veículo (Ex: ABC-1234)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(help_text='Modelo do carro (Ex: Fusca, Uno)', max_length=100, verbose_name='Modelo')),
                ('cor', models.CharField(help_text='Cor do carro (Ex: Vermelho, Prata)', max_length=50, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': [django.db.models.functions.text.Upper('modelo'), 'placa'],
            },
        ),
    ]
