# Generated by Django 5.2.7 on 2025-11-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carros', '0001_initial'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='carros_pertencentes', to='Clientes.cliente', verbose_name='Clientes Associados'),
        ),
    ]
