# Generated by Django 5.2.7 on 2025-11-18 12:39

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carros', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': [django.db.models.functions.text.Upper('modelo'), 'placa'], 'permissions': (('visualizar_carro', 'Pode visualizar a lista e detalhes de carros'), ('cadastrar_carro', 'Pode adicionar novos carros'), ('editar_carro', 'Pode editar carros existentes'), ('deletar_carro', 'Pode excluir carros')), 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
