# Generated by Django 5.2.6 on 2025-09-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('pessoas_fisicas', '0001_initial'),
        ('precos', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('pernoite', models.BooleanField(default=False)),
                ('relatorio', models.TextField(blank=True, null=True)),
                ('pagamento_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamentos_cliente', to='pessoas_fisicas.pessoafisica')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamentos_funcionario', to='funcionarios.funcionario')),
                ('preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='precos.preco')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
        ),
    ]
