# Generated by Django 5.2.7 on 2025-11-19 00:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo ou razão social', max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='CPF para Pessoa Física, CNPJ para Pessoa Jurídica', max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('fone', models.CharField(help_text='Número do telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.CharField(help_text='Endereço de Email', max_length=100, unique=True, verbose_name='Email')),
                ('carros', models.ManyToManyField(blank=True, to='Carros.carro', verbose_name='Carros do Cliente')),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('nome')],
                'permissions': (('visualizar_cliente', 'Pode visualizar a lista e detalhes de clientes'), ('cadastrar_cliente', 'Pode adicionar novos clientes'), ('editar_cliente', 'Pode editar clientes existentes'), ('deletar_cliente', 'Pode excluir clientes')),
                'abstract': False,
            },
        ),
    ]
