# Generated by Django 5.2.7 on 2025-11-18 12:37

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'permissions': (('visualizar_cliente', 'Pode visualizar a lista e detalhes de clientes'), ('cadastrar_cliente', 'Pode adicionar novos clientes'), ('editar_cliente', 'Pode editar clientes existentes'), ('deletar_cliente', 'Pode excluir clientes'))},
        ),
    ]
